import {
  Doc,
  Paragraph,
  Blockquote,
  HorizontalRule,
  Heading,
  Text,
  CodeBlock,
  // BulletList,
  // OrderedList,
  // ListItem,
  Image,
  HardBreak,
  Table,
  TableRow,
  TableColumn,
  TableCell,
  TableHeader,
} from './index';

export default [
  new Doc(),
  new Paragraph(),
  new Blockquote(),
  new HorizontalRule(),
  new Heading(),
  new Text(),
  new CodeBlock(),
  // new BulletList(),
  // new OrderedList(),
  // new ListItem(),
  new Image(),
  new HardBreak(),
  new Table(),
  new TableRow(),
  new TableColumn(),
  new TableCell(),
  new TableHeader()
];
